# Generated by Django 4.2.2 on 2023-07-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("investment_code", models.CharField(max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
