# Generated by Django 4.2.2 on 2023-08-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="institution",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        ),
    ]
